dist: focal

language: c++

services:
  - docker

before_install:
  - docker build -t test docker/Dockerfile
  - docker run -it -v ./:/home/developer/github -d test --name basic_environment

script:
  - docker exec basic_environment bash -c "cd /home/developer/github; bazel test //:test_suite"
