dist: focal

language: c++

services:
  - docker

before_install:
  - cd docker; docker build -t test .; cd ..
  - echo ${TRAVIS_BUILD_DIR}

script:
  - docker run -it -v ${TRAVIS_BUILD_DIR}:/home/developer/github test bash -c "cd /home/developer/github; bazel test //:test_suite"
