dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/6.0.0-pre.20220421.3/bazel-6.0.0-pre.20220421.3-installer-linux-x86_64.sh 
  - wget https://github.com/bazelbuild/bazel/releases/download/6.0.0-pre.20220421.3/bazel-6.0.0-pre.20220421.3-installer-linux-x86_64.sh.sha256
  - sha256sum -c  bazel-6.0.0-pre.20220421.3-installer-linux-x86_64.sh.sha256
  - sudo bash bazel-6.0.0-pre.20220421.3-installer-linux-x86_64.sh.sha256

script:
  - bazel test //:test_suite
